//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GI_VideoVersions.res.lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CHS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CHS() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GI_VideoVersions.res.lang.CHS", typeof(CHS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 导出... 的本地化字符串。
        /// </summary>
        internal static string BtnExport {
            get {
                return ResourceManager.GetString("BtnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并... 的本地化字符串。
        /// </summary>
        internal static string BtnMerge {
            get {
                return ResourceManager.GetString("BtnMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string CtxItemCopy {
            get {
                return ResourceManager.GetString("CtxItemCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持的游戏版本： 的本地化字符串。
        /// </summary>
        internal static string LabGameVer {
            get {
                return ResourceManager.GetString("LabGameVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示语言 的本地化字符串。
        /// </summary>
        internal static string LabLanguage {
            get {
                return ResourceManager.GetString("LabLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程ID 的本地化字符串。
        /// </summary>
        internal static string LabProcessId {
            get {
                return ResourceManager.GetString("LabProcessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接状态 的本地化字符串。
        /// </summary>
        internal static string LabStatus {
            get {
                return ResourceManager.GetString("LabStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认断开连接？
        ///同一进程将不会重复被自动附加。 的本地化字符串。
        /// </summary>
        internal static string MsgConfirmDisconnect {
            get {
                return ResourceManager.GetString("MsgConfirmDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定退出吗？
        ///请确认所有获取到的密钥已被保存！ 的本地化字符串。
        /// </summary>
        internal static string MsgConfirmExit {
            get {
                return ResourceManager.GetString("MsgConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接到进程 {0} 失败！
        ///错误：{1} 的本地化字符串。
        /// </summary>
        internal static string MsgConnectFail {
            get {
                return ResourceManager.GetString("MsgConnectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程 {0} 连接已中断！ 的本地化字符串。
        /// </summary>
        internal static string MsgConnectionLost {
            get {
                return ResourceManager.GetString("MsgConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从 26236578.blk 获取 versions.json 失败！
        ///错误: {0} 的本地化字符串。
        /// </summary>
        internal static string MsgDumpListFail {
            get {
                return ResourceManager.GetString("MsgDumpListFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载动态链接库 {0} 失败！
        ///错误：{1} 的本地化字符串。
        /// </summary>
        internal static string MsgLoadDllFail {
            get {
                return ResourceManager.GetString("MsgLoadDllFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件 {0} 失败！
        ///错误：{1} 的本地化字符串。
        /// </summary>
        internal static string MsgOpenFileFail {
            get {
                return ResourceManager.GetString("MsgOpenFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法获取管理员权限！
        ///请以管理员身份重新运行本程序... 的本地化字符串。
        /// </summary>
        internal static string MsgRequireAdmin {
            get {
                return ResourceManager.GetString("MsgRequireAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存文件 {0} 失败！
        ///错误: {1} 的本地化字符串。
        /// </summary>
        internal static string MsgSaveFileFail {
            get {
                return ResourceManager.GetString("MsgSaveFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接 的本地化字符串。
        /// </summary>
        internal static string TxtConnected {
            get {
                return ResourceManager.GetString("TxtConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接中... 的本地化字符串。
        /// </summary>
        internal static string TxtConnecting {
            get {
                return ResourceManager.GetString("TxtConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未连接 的本地化字符串。
        /// </summary>
        internal static string TxtDisconnect {
            get {
                return ResourceManager.GetString("TxtDisconnect", resourceCulture);
            }
        }
    }
}
