//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GI_VideoVersions.res.lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_cn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_cn() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GI_VideoVersions.res.lang.zh_cn", typeof(zh_cn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string CtxItemCopy {
            get {
                return ResourceManager.GetString("CtxItemCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持的游戏版本： 的本地化字符串。
        /// </summary>
        internal static string LabGameVer {
            get {
                return ResourceManager.GetString("LabGameVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示语言 的本地化字符串。
        /// </summary>
        internal static string LabLanguage {
            get {
                return ResourceManager.GetString("LabLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程ID 的本地化字符串。
        /// </summary>
        internal static string LabProcessId {
            get {
                return ResourceManager.GetString("LabProcessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接状态 的本地化字符串。
        /// </summary>
        internal static string LabStatus {
            get {
                return ResourceManager.GetString("LabStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接到进程 {0} 失败！
        ///错误：{1} 的本地化字符串。
        /// </summary>
        internal static string MsgConnectFail {
            get {
                return ResourceManager.GetString("MsgConnectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 26236578.blk 内容失败！ 的本地化字符串。
        /// </summary>
        internal static string MsgDumpListFail {
            get {
                return ResourceManager.GetString("MsgDumpListFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存文件 {0} 失败！ 的本地化字符串。
        /// </summary>
        internal static string MsgSaveFileFail {
            get {
                return ResourceManager.GetString("MsgSaveFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接 的本地化字符串。
        /// </summary>
        internal static string TxtConnected {
            get {
                return ResourceManager.GetString("TxtConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接中... 的本地化字符串。
        /// </summary>
        internal static string TxtConnecting {
            get {
                return ResourceManager.GetString("TxtConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未连接 的本地化字符串。
        /// </summary>
        internal static string TxtDisconnect {
            get {
                return ResourceManager.GetString("TxtDisconnect", resourceCulture);
            }
        }
    }
}
